export const COLOMBIA_DEPARTMENTS = [
  'Amazonas','Antioquia','Arauca','Atlántico','Bolívar','Boyacá','Caldas','Caquetá',
  'Casanare','Cauca','Cesar','Chocó','Córdoba','Cundinamarca','Guainía','Guaviare',
  'Huila','La Guajira','Magdalena','Meta','Nariño','Norte de Santander','Putumayo',
  'Quindío','Risaralda','San Andrés y Providencia','Santander','Sucre','Tolima',
  'Valle del Cauca','Vaupés','Vichada','Bogotá D.C.'
];

export const COLOMBIA_MUNICIPALITIES: Record<string, string[]> = {
  'Amazonas': ['Leticia','Puerto Nariño','La Pedrera','El Encanto','Tarapacá'],
  'Antioquia': ['Medellín','Bello','Envigado','Itagüí','Sabaneta','Rionegro','Marinilla','La Ceja','El Retiro','Copacabana','Girardota','Barbosa','Caldas','La Estrella','Amagá','Apartadó','Turbo','Carepa','Chigorodó','Arboletes','Cañasgordas','Frontino','Santa Fe de Antioquia','Yarumal','Santa Rosa de Osos','Donmatías','Entrerríos','Puerto Berrío','Puerto Nare','Puerto Triunfo','Segovia','Remedios','Caucasia','Cáceres','Necoclí','San Pedro de Urabá','Concordia','Betania','Ciudad Bolívar','Urrao','Jardín','Andes','Venecia','Fredonia','Jericó','Támesis','Titiribí','Abejorral','Sonsón','Aguadas','Pácora','Salamina','Argelia','Nariño','San Carlos','Granada','Guatapé','San Rafael','San Roque','Yolombó','Cisneros','San Jerónimo','Ebéjico','Heliconia','Sopetrán','Belmira','San Andrés de Cuerquia','Carolina del Príncipe','Angostura','Campamento','Yalí','Vegachí','Maceo','Caracolí','San Francisco','Cocorná','El Peñol','San Vicente'],
  'Arauca': ['Arauca','Arauquita','Cravo Norte','Fortul','Puerto Rondón','Saravena','Tame'],
  'Atlántico': ['Barranquilla','Soledad','Malambo','Puerto Colombia','Galapa','Juan de Acosta','Piojó','Tubará','Usiacurí','Sabanagrande','Santo Tomás','Palmar de Varela','Ponedera','Candelaria','Campo de la Cruz','Luruaco','Repelón','Manatí','Suan','Santa Lucía'],
  'Bolívar': ['Cartagena de Indias','Magangué','Turbaco','Arjona','El Carmen de Bolívar','María La Baja','San Juan Nepomuceno','Calamar','Mompox','Achí','Altos del Rosario','Barranco de Loba','Simití','San Pablo','Cantagallo','Norosí','Río Viejo','Tiquisio','Montecristo','Santa Rosa del Sur','San Martín de Loba','Regidor','El Peñón','Hatillo de Loba','San Jacinto','San Cristóbal','Villanueva','Soplaviento','Mahates','San Estanislao','Arroyohondo','Clemencia','Santa Catalina','Santa Rosa de Lima','Córdoba','El Guamo','Pinillos','Margarita','Cicuco','San Fernando','Talaigua Nuevo','Majagual','Sucre'],
  'Boyacá': ['Tunja','Duitama','Sogamoso','Chiquinquirá','Paipa','Socotá','Miraflores','Moniquirá','Ráquira','Villa de Leyva','Garagoa','Guateque','Somondoco','Sutamarchán','Tinjacá','Sáchica','Chíquiza','Cómbita','Oicatá','Sotaquirá','Tuta','Ventaquemada','Nobsa','Corrales','Tópaga','Mongua','Monguí','Gámeza','Tasco','Socha','Tota','Aquitania','Cultiva','Pesca','Firavitoba','Iza','Cuítiva','Santa Rosa de Viterbo','Cerinza','Belen','Floresta','Betéitiva','Busbanzá','Paz de Río','Sativasur'],
  'Caldas': ['Manizales','Villamaría','Chinchiná','Neira','Palestina','Aguadas','Pácora','Salamina','Aranzazu','Filadelfia','La Merced','Marmato','Riosucio','Supía','Anserma','Belalcázar','San José','Viterbo','La Dorada','Norcasia','Samaná','Victoria','Marulanda','Manzanares','Pensilvania'],
  'Caquetá': ['Florencia','La Montañita','El Paujil','Belén de los Andaquíes','San Vicente del Caguán','Cartagena del Chairá','Curillo','Milán','Morelia','Puerto Rico','San José del Fragua','Solano','Solita','Valparaíso','Albania','San Antonio de Getuchá'],
  'Casanare': ['Yopal','Aguazul','Villanueva','Paz de Ariporo','Tauramena','Maní','Monterrey','Trinidad','San Luis de Palenque','Hato Corozal','Pore','Nunchía','Támara','Sabanalarga','Recetor','Chámeza','La Salina','Sácama'],
  'Cauca': ['Popayán','Santander de Quilichao','Puerto Tejada','Caldono','Guachené','Miranda','Padilla','Corinto','Florida','Cajibío','El Tambo','Silvia','Piendamó','Morales','Suárez','Buenos Aires','López de Micay','Guapi','Timbiquí','Balboa','Argelia','Almaguer','Bolívar','La Vega','Patía','Rosas','Timbío','Puracé','San Sebastián','Totoró','Inzá','Jambaló','Toribío','Páez','Guadalupe'],
  'Cesar': ['Valledupar','Aguachica','Agustín Codazzi','La Jagua de Ibirico','Bosconia','El Copey','Curumaní','Chimichagua','Pailitas','San Alberto','San Martín','Gamarra','La Paz','Manaure Balcón del Cesar','Pueblo Bello','Río de Oro','Becerril','Codazzi','González','Tamalameque'],
  'Chocó': ['Quibdó','Istmina','Condoto','Tadó','Nuquí','Bahía Solano','Juradó','Riosucio','Carmen del Darién','Acandí','Unguía','El Cantón de San Pablo','Bojayá','Lloró','Atrato','Bagadó','Cértegui','Sipí','Novita','San José del Palmar','El Carmen de Atrato','Unión Panamericana','Medio San Juan','Medio Atrato','Alto Baudó','Bajo Baudó'],
  'Córdoba': ['Montería','Cereté','San Pelayo','Ciénaga de Oro','San Carlos','Planeta Rica','Montelíbano','Sahagún','Chinú','Tuchín','San Andrés de Sotavento','Lorica','Purísima','Momil','San Bernardo del Viento','Moñitos','Puerto Escondido','Los Córdobas','San Antero','Coveñas','Tolú','San Antonio de Palmito','La Apartada','Puerto Libertador','Ayapel','Buenavista','La Unión','Valencia','Tierralta','Canalete'],
  'Cundinamarca': ['Bogotá D.C.','Soacha','Zipaquirá','Chía','Cajicá','Madrid','Mosquera','Funza','Facatativá','El Rosal','Subachoque','Tabio','Tenjo','Cota','Sopó','Tocancipá','Gachancipá','Nemocón','Suesca','Chocontá','Villapinzón','Ubaté','Simijaca','Susa','Lenguazaque','Cucunubá','Carmen de Carupa','Guachetá','Guatavita','Gachetá','Junín','La Calera','Guasca','Sibaté','Fusagasugá','Silvania','Tibacuy','Arbeláez','Pasca','San Bernardo','Venecia','Cabrera','Granada','Sasaima','Villeta','Guaduas','Vianí','Beltrán','Pulí','Jerusalén','Quipile','Anapoima','Apulo','Tocaima','Agua de Dios','Nilo','La Mesa','El Colegio','San Antonio del Tequendama','Bojacá','Zipacón','La Vega','San Francisco','Nocaima','Vergara','El Peñón','La Palma','Pacho'],
  'Guainía': ['Inírida','Barrancominas','Cacahual','La Guadalupe','Mapiripana','Morichal','Pana Pana','Puerto Colombia','San Felipe'],
  'Guaviare': ['San José del Guaviare','Calamar','El Retorno','Miraflores'],
  'Huila': ['Neiva','Pitalito','Garzón','La Plata','Campoalegre','Rivera','Palermo','Aipe','Villavieja','Tello','Baraya','Colombia','Teruel','Yaguará','Hobo','Suaza','Guadalupe','Altamira','Timaná','Elías','Oporapa','Saladoblanco','Isnos','San Agustín','Palestina','Pital','Agrado','Gigante','Tesalia','Paicol','Nátaga','Iquira','Santa María'],
  'La Guajira': ['Riohacha','Maicao','Uribia','Manaure','Hatonuevo','Barrancas','Fonseca','San Juan del Cesar','Villanueva','El Molino','Distracción','La Jagua del Pilar','Urumita','Albania','Dibulla','El Cerrito'],
  'Magdalena': ['Santa Marta','Ciénaga','Aracataca','Fundación','El Banco','Pivijay','Plato','Ariguaní','Zona Bananera','Cerro de San Antonio','Pedraza','Pijiño del Carmen','Remolino','Salamina','Sitionuevo','Concordia','San Zenón','Santa Ana','Santa Bárbara de Pinto','Pueblo Viejo','Tenerife','Guamal','San Sebastián de Buenavista','San Miguel'],
  'Meta': ['Villavicencio','Acacías','Granada','Puerto López','Restrepo','Cumaral','Puerto Gaitán','San Martín','Puerto Lleras','Vistahermosa','San Juan de Arama','San Carlos de Guaroa','Cabuyaro','Puerto Concordia','La Macarena','Mapiripán','El Castillo','Lejanías','Cubarral','El Dorado','Fuente de Oro','Guamal','Castilla la Nueva','Barranca de Upía'],
  'Nariño': ['Pasto','Tumaco','Ipiales','Tuquerres','Barbacoas','Cumbal','Guachucal','La Unión','Samaniego','Sandoná','Consacá','Ancuya','Imués','Ospina','Guaitarilla','El Tambo','Tangua','Yacuanquer','Sapuyes','Potosí','Gualmatán','Córdoba','Pupiales','Contadero','Iles','Cuaspud','Carlosama','Ricaurte','Cumbitara','El Charco','La Tola','Olaya Herrera','Mosquera','Roberto Payán','San Andrés de Tumaco','Francisco Pizarro','Santa Bárbara','Magüí','Policarpa','Arboleda','Berruecos','San Lorenzo','Taminango','El Peñol','Los Andes','Chachagüí'],
  'Norte de Santander': ['Cúcuta','Ocaña','Pamplona','Los Patios','Villa del Rosario','El Zulia','Puerto Santander','San Cayetano','Santiago','La Esperanza','Gramalote','Lourdes','Chinácota','Ragonvalia','Herrán','Toledo','Labateca','Cucutilla','Arboledas','Cachirá','El Carmen','Convención','Teorama','Ábrego','La Playa de Belén','Hacarí','San Calixto','Sardinata','El Tarra','Tibú','Bucarasica','Durania','Bochalema'],
  'Putumayo': ['Mocoa','Puerto Asís','Orito','Valle del Guamuez','La Hormiga','San Miguel','Puerto Caicedo','Puerto Guzmán','Puerto Leguízamo','Sibundoy','Colón','San Francisco','Santiago','Villagarzón'],
  'Quindío': ['Armenia','Calarcá','La Tebaida','Montenegro','Quimbaya','Salento','Buenavista','Córdoba','Filandia','Génova','Pijao','Circasia','Barcelona'],
  'Risaralda': ['Pereira','Dosquebradas','Santa Rosa de Cabal','La Virginia','Belén de Umbría','Apía','Santuario','Balboa','La Celia','Guática','Quinchía','Mistrató','Pueblo Rico','Marsella'],
  'San Andrés y Providencia': ['San Andrés','Providencia','Santa Catalina'],
  'Santander': ['Bucaramanga','Floridablanca','Girón','Piedecuesta','Barrancabermeja','Lebrija','Rionegro','Sabana de Torres','Puerto Wilches','El Playón','Matanza','California','Vetas','Suratá','Carcasí','Enciso','Guaca','Málaga','Molagavita','San Andrés','San José de Miranda','San Miguel','Concepción','Cerrito','Santa Bárbara','Capitanejo','San Gil','Socorro','Barichara','Villanueva','Charalá','Curití','Pinchote','San Joaquín','Valle de San José','Oiba','Guapotá','El Carmen de Chucurí','Puerto Parra','Landázuri','Cimitarra','Bolívar','Sucre','La Paz','San Vicente de Chucurí','Vélez','Barbosa','Puente Nacional','Jesús María','Guavatá','Suaita','San Benito','Güepsa','Aguada','La Belleza','Chipatá'],
  'Sucre': ['Sincelejo','Corozal','Sampués','Sincé','Galeras','Morroa','Coveñas','Tolú','Chalán','Colosó','Los Palmitos','San Antonio de Palmito','San Juan de Betulia','Ovejas','Caimito','La Unión','Palmito','Puerto Sucre','Majagual','San Marcos','San Benito Abad','Guaranda','Sucre'],
  'Tolima': ['Ibagué','Espinal','Flandes','Líbano','Honda','Melgar','Lérida','Chaparral','Purificación','Mariquita','Armero Guayabal','Venadillo','Guamo','Saldaña','Rovira','San Luis','Ortega','Roncesvalles','San Antonio','Valle de San Juan','Suárez','Alvarado','Piedras','Ambalema','Herveo','Palocabildo','Villahermosa','Casabianca','Murillo','Santa Isabel','Anzoátegui','Fresno'],
  'Valle del Cauca': ['Cali','Palmira','Buenaventura','Tuluá','Cartago','Buga','Jamundí','Yumbo','Florida','Pradera','Candelaria','El Cerrito','Guacarí','Ginebra','La Cumbre','Restrepo','Yotoco','Bolívar','Roldanillo','La Unión','Toro','Zarzal','Obando','Caicedonia','Sevilla','El Dovio','Versalles','El Cairo','Argelia','Ansermanuevo','Trujillo','Riofrío','Dagua','Bugalagrande','Andalucía','San Pedro'],
  'Vaupés': ['Mitú','Caruru','Papunaua','Taraira','Yavaraté','Pacoa','Papunahua'],
  'Vichada': ['Puerto Carreño','La Primavera','Santa Rosalía','Cumaribo'],
  'Bogotá D.C.': ['Bogotá D.C.','Usaquén','Chapinero','Santa Fe','San Cristóbal','Usme','Tunjuelito','Bosa','Kennedy','Fontibón','Engativá','Suba','Barrios Unidos','Teusaquillo','Los Mártires','Antonio Nariño','Puente Aranda','La Candelaria','Rafael Uribe','Ciudad Bolívar','Sumapaz'],
};

const FLAG_CDN = 'https://flagcdn.com/24x18';

export const PHONE_COUNTRIES = [
  { code: '+57', country: 'Colombia', flag: `${FLAG_CDN}/co.png`, placeholder: '300 000 0000' },
  { code: '+1', country: 'Estados Unidos', flag: `${FLAG_CDN}/us.png`, placeholder: '555 000 0000' },
  { code: '+52', country: 'México', flag: `${FLAG_CDN}/mx.png`, placeholder: '55 0000 0000' },
  { code: '+34', country: 'España', flag: `${FLAG_CDN}/es.png`, placeholder: '600 000 000' },
  { code: '+58', country: 'Venezuela', flag: `${FLAG_CDN}/ve.png`, placeholder: '412 000 0000' },
  { code: '+54', country: 'Argentina', flag: `${FLAG_CDN}/ar.png`, placeholder: '11 0000 0000' },
  { code: '+56', country: 'Chile', flag: `${FLAG_CDN}/cl.png`, placeholder: '9 0000 0000' },
  { code: '+51', country: 'Perú', flag: `${FLAG_CDN}/pe.png`, placeholder: '900 000 000' },
  { code: '+593', country: 'Ecuador', flag: `${FLAG_CDN}/ec.png`, placeholder: '99 000 0000' },
  { code: '+591', country: 'Bolivia', flag: `${FLAG_CDN}/bo.png`, placeholder: '700 00000' },
  { code: '+595', country: 'Paraguay', flag: `${FLAG_CDN}/py.png`, placeholder: '961 000 000' },
  { code: '+598', country: 'Uruguay', flag: `${FLAG_CDN}/uy.png`, placeholder: '99 000 000' },
  { code: '+507', country: 'Panamá', flag: `${FLAG_CDN}/pa.png`, placeholder: '6000 0000' },
  { code: '+506', country: 'Costa Rica', flag: `${FLAG_CDN}/cr.png`, placeholder: '6000 0000' },
  { code: '+505', country: 'Nicaragua', flag: `${FLAG_CDN}/ni.png`, placeholder: '8000 0000' },
  { code: '+503', country: 'El Salvador', flag: `${FLAG_CDN}/sv.png`, placeholder: '7000 0000' },
  { code: '+502', country: 'Guatemala', flag: `${FLAG_CDN}/gt.png`, placeholder: '5000 0000' },
  { code: '+504', country: 'Honduras', flag: `${FLAG_CDN}/hn.png`, placeholder: '9000 0000' },
  { code: '+1-809', country: 'República Dominicana', flag: `${FLAG_CDN}/do.png`, placeholder: '809 000 0000' },
  { code: '+53', country: 'Cuba', flag: `${FLAG_CDN}/cu.png`, placeholder: '5 000 0000' },
  { code: '+44', country: 'Reino Unido', flag: `${FLAG_CDN}/gb.png`, placeholder: '7000 000000' },
  { code: '+33', country: 'Francia', flag: `${FLAG_CDN}/fr.png`, placeholder: '6 00 00 00 00' },
  { code: '+49', country: 'Alemania', flag: `${FLAG_CDN}/de.png`, placeholder: '151 00000000' },
  { code: '+39', country: 'Italia', flag: `${FLAG_CDN}/it.png`, placeholder: '300 000 0000' },
  { code: '+351', country: 'Portugal', flag: `${FLAG_CDN}/pt.png`, placeholder: '900 000 000' },
  { code: '+55', country: 'Brasil', flag: `${FLAG_CDN}/br.png`, placeholder: '11 90000 0000' },
  { code: '+41', country: 'Suiza', flag: `${FLAG_CDN}/ch.png`, placeholder: '79 000 00 00' },
  { code: '+61', country: 'Australia', flag: `${FLAG_CDN}/au.png`, placeholder: '400 000 000' },
  { code: '+64', country: 'Nueva Zelanda', flag: `${FLAG_CDN}/nz.png`, placeholder: '20 000 0000' },
  { code: '+81', country: 'Japón', flag: `${FLAG_CDN}/jp.png`, placeholder: '90 0000 0000' },
  { code: '+82', country: 'Corea del Sur', flag: `${FLAG_CDN}/kr.png`, placeholder: '10 0000 0000' },
  { code: '+86', country: 'China', flag: `${FLAG_CDN}/cn.png`, placeholder: '130 0000 0000' },
  { code: '+91', country: 'India', flag: `${FLAG_CDN}/in.png`, placeholder: '90000 00000' },
];